# config/credentials.yml (this is what you edit, gets encrypted to .yml.enc)
development:
  database:
    password: your_dev_db_password
  aws:
    access_key_id: your_aws_key
    secret_access_key: your_aws_secret
  some_api_key: your_api_key_here

production:
  database:
    password: <%= ENV['DATABASE_PASSWORD'] %>
  aws:
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: your_generated_secret_key_base_will_be_here_automatically
